"""
PDF Report Generation Service using fpdf2.
Generates professional crime report PDFs for police escalation.
"""
from fpdf import FPDF
from datetime import datetime
import io


class CrimeReportPDF(FPDF):
    """Custom PDF class with header/footer for Vigilo reports."""

    def header(self):
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(30, 58, 138)  # Dark blue
        self.cell(0, 10, "VIGILO - CrimeSafe AI", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 5, "Official Crime Report for Police Escalation", align="C", new_x="LMARGIN", new_y="NEXT")
        self.line(10, 28, 200, 28)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by Vigilo Platform  |  Page {self.page_no()}/{{nb}}  |  {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(30, 58, 138)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(30, 58, 138)
        self.line(self.get_x(), self.get_y(), self.get_x() + 50, self.get_y())
        self.ln(3)

    def field(self, label: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(60, 60, 60)
        self.cell(50, 7, f"{label}:", new_x="END")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(30, 30, 30)
        self.multi_cell(0, 7, str(value) if value else "N/A")
        self.ln(1)


def generate_report_pdf(report) -> bytes:
    """
    Generate a PDF for a given CrimeReport SQLAlchemy model instance.
    Returns bytes of the PDF.
    """
    pdf = CrimeReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()

    # ── Report Summary ──
    pdf.section_title("Report Summary")
    pdf.field("Report ID", report.report_id)
    pdf.field("Status", report.status.upper())
    pdf.field("Crime Type", report.crime_type)
    pdf.field("Severity", report.severity)
    pdf.field("Date Occurred", report.date_occurred.strftime("%B %d, %Y at %I:%M %p") if report.date_occurred else "Unknown")
    pdf.field("Time of Day", report.time_of_day or "Not specified")
    pdf.ln(4)

    # ── Location ──
    pdf.section_title("Location Details")
    pdf.field("Area Name", report.area_name or "Surat")
    pdf.field("Latitude", f"{report.latitude:.6f}")
    pdf.field("Longitude", f"{report.longitude:.6f}")
    maps_url = f"https://maps.google.com/?q={report.latitude},{report.longitude}"
    pdf.field("Google Maps", maps_url)
    pdf.ln(4)

    # ── Description ──
    pdf.section_title("Incident Description")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(30, 30, 30)
    desc = report.description or "No description provided."
    clean_desc = desc.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 6, clean_desc)
    pdf.ln(6)

    # ── AI Verification ──
    pdf.section_title("AI Verification Analysis")
    trust_pct = f"{report.trust_score:.1f}%" if report.trust_score else "N/A"
    pdf.field("Trust Score", trust_pct)

    if report.admin_notes:
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 50)
        
        # Clean up emoji for PDF compatibility
        clean_notes = report.admin_notes
        for emoji_tuple in [("✅", ""), ("❌", ""), ("⚠️", ""), ("ℹ️", ""), ("➡️", "->"), ("📝", ""), ("•", "-"), ("📷", ""), ("🚨", ""), ("🚔", "")]:
            clean_notes = clean_notes.replace(emoji_tuple[0], emoji_tuple[1])
            
        # Final safety encoding for raw fpdf Helvetica
        clean_notes = clean_notes.encode('latin-1', 'ignore').decode('latin-1')
        pdf.multi_cell(0, 5, clean_notes)
    pdf.ln(6)

    # ── Evidence ──
    if report.media_urls and len(report.media_urls) > 0:
        pdf.section_title("Attached Evidence")
        for i, url in enumerate(report.media_urls):
            pdf.field(f"File {i+1}", url)
    
    # ── Footer note ──
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "This report was automatically generated by the Vigilo CrimeSafe AI platform. "
                         "All data has been verified through our AI analysis pipeline. "
                         "For questions, contact the Vigilo administration team.")

    return bytes(pdf.output())
