export const POI_CATALOG = [
  {
    id: "cb-patel-computer-college",
    label: "C B Patel Computer College",
    category: "College",
    address: "5Q2X+RJQ, New City Light Road, Bharthana, Vesu, Surat, Gujarat 395007",
    phone: "0261 226 2951",
    hours: "Open 24 hours",
    query: "C B Patel Computer College, New City Light Road, Bharthana, Vesu, Surat 395007",
    lat: 21.1520806,
    lon: 72.7989993,
  },
  {
    id: "shilp-residency",
    label: "Shilp Residency",
    category: "Apartment complex",
    address: "Shilp Residency, Vesu water tank, A, VIP Rd, behind Shubh Residency, Ward 2, Vesu, Surat, Gujarat 395007",
    phone: "N/A",
    hours: "Open 24 hours",
    query: "Shilp Residency, VIP Rd, Vesu, Surat",
    lat: 21.149,
    lon: 72.784,
  },
  {
    id: "vr-surat",
    label: "VR Surat",
    category: "Shopping mall",
    address: "Dumas Rd, Magdalla, Surat, Gujarat 395007",
    phone: "0261 679 5001",
    hours: "Open · Closes 9:30 pm",
    query: "VR Surat, Dumas Rd, Magdalla, Surat, Gujarat 395007",
    lat: 21.1444,
    lon: 72.7719,
  },
  {
    id: "rr-mall",
    label: "Rahul Raj Mall",
    category: "Shopping mall",
    address: "Near Gaurav Path, Dumas Rd, opposite Shri Govardhannathji Ki Haveli, Piplod, Surat, Gujarat 395007",
    phone: "063511 87597",
    hours: "Open · Closes 10 pm",
    query: "Rahul Raj Mall, RR Mall, Gaurav Path, Dumas Rd, Piplod",
    lat: 21.1545,
    lon: 72.7845,
  },
  {
    id: "aagam-arcade",
    label: "Aagam Arcade",
    category: "Shopping mall",
    address: "Aagam Arcade, Vesu Main Road, opposite Jolly Residency, Vesu, Surat, Gujarat 395007",
    phone: "N/A",
    hours: "Open · Closes 11 pm",
    query: "Aagam Arcade, Vesu Main Road, Surat",
    lat: 21.1440,
    lon: 72.7845,
  },
  {
    id: "lake-view-garden",
    label: "Lake View Garden",
    category: "Park & Garden",
    address: "5Q8J+5G9, Dumas Rd, SVNIT Campus, Athwa, Pipelod, Surat, Gujarat 395007",
    phone: "N/A",
    hours: "4:00 PM - 10:00 PM",
    query: "Lake View Garden, Piplod, Surat",
    lat: 21.1565,
    lon: 72.7758,
  },
  {
    id: "dumas-sea-face",
    label: "Dumas Sea Face",
    category: "Beach & Landmark",
    address: "3PJ5+XJW, Dumas, Gujarat 394550",
    phone: "N/A",
    hours: "Open · Closes 7:00 PM",
    query: "Dumas Sea Face, Dumas Beach, Surat",
    lat: 21.0792,
    lon: 72.7153,
  }
];
